"""Staleness stamps for shared data artifacts.

Data-producing stages stamp their product roots with the input hash and run
id that generated them. Consumer stages re-read the stamps they observed and
fail fast when another run has rewritten the artifacts mid-flight, instead of
silently consuming a foreign run's data.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

from panelcast.pipelines.errors import StaleArtifactError

STAMP_FILENAME = ".stamp.json"

# Product roots stamped by each data-producing stage.
DATA_STAGE_ROOTS: dict[str, Path] = {
    "data": Path("data/processed"),
    "splits": Path("data/splits"),
    "features": Path("data/features"),
}

# Stages that read the stamped roots and must not consume foreign artifacts.
CONSUMER_STAGES = frozenset({"train", "evaluate", "predict", "sensitivity"})


def stamp_path(root: Path) -> Path:
    """Path of the stamp file for a data product root."""
    return Path(root) / STAMP_FILENAME


def write_stamp(root: Path, stage: str, input_hash: str, run_id: str) -> dict:
    """Write a stamp beside a data product and return its payload."""
    payload = {
        "stage": stage,
        "input_hash": input_hash,
        "run_id": run_id,
        "written_at": datetime.now(timezone.utc).isoformat(),
    }
    path = stamp_path(root)
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(path.name + ".tmp")
    tmp.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    tmp.replace(path)
    return payload


def read_stamp(root: Path) -> dict | None:
    """Read a product root's stamp, or None if absent or unreadable."""
    path = stamp_path(root)
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None


def verify_stamps(observed: dict[str, dict], consumer: str) -> None:
    """Fail fast if any observed stamp was rewritten by another run.

    ``observed`` maps data-stage names to the stamp payload this run saw when
    it prepared (or first consumed) the artifacts. A missing current stamp is
    tolerated (pre-stamp artifacts); a differing one is a hard error.
    """
    for stage_name, recorded in observed.items():
        root = DATA_STAGE_ROOTS.get(stage_name)
        if root is None or not recorded:
            continue
        current = read_stamp(root)
        if current is None:
            continue
        same_run = current.get("run_id") == recorded.get("run_id")
        same_inputs = current.get("input_hash") == recorded.get("input_hash")
        if not (same_run and same_inputs):
            raise StaleArtifactError(
                f"{root.as_posix()} was regenerated by run "
                f"{current.get('run_id', 'unknown')} at "
                f"{current.get('written_at', 'unknown')} after run "
                f"{recorded.get('run_id', 'unknown')} prepared it. "
                f"Re-run the {stage_name} stage or start a fresh run.",
                stage=consumer,
            )
